# Microsoft JDBC Driver for SQL Server CI Build triggers tests against below SQL Servers:
#   - SQL Server 2017 for Linux

trigger:
- dev
pool:
  vmImage: 'Ubuntu-16.04'
steps:
- powershell:
    mkdir AE_Certificates
    cd AE_Certificates
    $cert = New-SelfSignedCertificate -dns "AlwaysEncryptedCert" -CertStoreLocation Cert:CurrentUser\My
    $pwd = ConvertTo-SecureString -String "password" -Force -AsPlainText
    $path = 'cert:\CurrentUser\My\' + $cert.thumbprint
    $certificate = Export-PfxCertificate -cert $path -FilePath cert.pfx -Password $pwd
    Get-ChildItem -path cert:\CurrentUser\My > certificate.txt
    keytool -importkeystore -srckeystore cert.pfx -srcstoretype pkcs12 -destkeystore clientcert.jks -deststoretype JKS -srcstorepass password -deststorepass password
    keytool -list -v -keystore clientcert.jks -storepass "password"> JavaKeyStoreBase.txt
    Get-Content .\JavaKeyStoreBase.txt | Set-Content -Encoding utf8 JavaKeyStore.txt
    Remove-Item –path .\JavaKeyStoreBase.txt
  displayName: 'Setup AE Certificates'
- script:
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild43
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42
- script:
    docker pull mcr.microsoft.com/mssql/server:latest
    export mssql_jdbc_logging='true'
    export SQLPWD=$(</dev/urandom tr -dc 'A-Za-z0-9#!' | head -c 15;)
    export mssql_jdbc_test_connection_properties="jdbc:sqlserver://localhost:1433;databaseName=master;username=sa;password=$SQLPWD"
    docker run -e 'ACCEPT_EULA=Y' -e "SA_PASSWORD=$SQLPWD" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
  displayName: 'Setup SQL Server Container'
- task: Maven@3
  displayName: 'Maven build 43'
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test -B -Pbuild43 jacoco:report && bash <(curl -s https://codecov.io/bash) -cF JDBC43'
- task: Maven@3
  displayName: 'Maven build 42'
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test -B -Pbuild42 jacoco:report && bash <(curl -s https://codecov.io/bash) -cF JDBC42'
