package com.microsoft.sqlserver.jdbc;

import java.util.*;

public final class SQLServerResource_sv extends ListResourceBundle {
    protected Object[][] getContents() {
        return contents;
    }

    static final Object[][] contents = {
        {"R_timedOutBeforeRouting","Tidsgränsen gick ut innan anslutningen till routningsmålet upprättades."},
        {"R_invalidRoutingInfo","Oväntad routningsinformation togs emot. Kontrollera anslutningsegenskaperna och konfigurationen av SQL Server."},
        {"R_multipleRedirections","Två eller fler omdirigeringar har gjorts. Bara en omdirigering får göras per inloggningsförsök."},
        {"R_dbMirroringWithMultiSubnetFailover","Det går inte att ansluta till en speglad SQL Server-instans med anslutningsegenskapen multiSubnetFailover."},
        {"R_dbMirroringWithReadOnlyIntent","Det går inte att ansluta till en speglad SQL Server-instans med anslutningsegenskapen ApplicationIntent ReadOnly."},
        {"R_ipAddressLimitWithMultiSubnetFailover","Det går inte att ansluta till en SQL Server-instans som konfigurerats med mer än {0} IP-adresser med anslutningsegenskapen multiSubnetFailover."},
        {"R_connectionTimedOut","Tidsgränsen för anslutningen gick ut: ingen ytterligare information ges"},
        {"R_invalidPositionIndex","Positionsindexet {0} är inte giltigt."},
        {"R_invalidLength","Längden {0} är inte giltig."},
        {"R_unknownSSType","SQL Server-datatypen {0} är ogiltig."},
        {"R_unknownJDBCType","JDBC-datatypen {0} är ogiltig."},
        {"R_notSQLServer","Drivrutinen mottog ett oväntat förinloggningssvar. Kontrollera anslutningsegenskaperna och att en instans av SQL Server körs på värddatorn som accepterar TCP/IP-anslutningar på porten. Den här drivrutinen kan endast användas med SQL Server 2000 eller senare."},
        {"R_tcpOpenFailed","{0}. Verifiera anslutningsegenskaperna. Kontrollera att en instans av SQL Server körs på värddatorn som accepterar TCP/IP-anslutningar på porten och att ingen brandvägg blockerar TCP-anslutningar till porten."},
        {"R_unsupportedJREVersion","JRE (Java Runtime Environment) version {0} stöds inte av den här drivrutinen. Använd klassbiblioteket sqljdbc4.jar som stöder JDBC 4.0."},
        {"R_unsupportedServerVersion","SQL Server version {0} stöds inte av den här drivrutinen."},
        {"R_noServerResponse","SQL Server returnerade inget svar. Anslutningen har kopplats från."},
        {"R_truncatedServerResponse","SQL Server returnerade ett ofullständigt svar. Anslutningen har kopplats från."},
        {"R_queryTimedOut","Frågan tog för lång tid."},
        {"R_queryCancelled","Frågan avbröts."},
        {"R_errorReadingStream","Ett fel uppstod när värdet från dataströmobjektet lästes. Fel: {0}"},
        {"R_streamReadReturnedInvalidValue","Läsåtgärden för strömmen returnerade ett ogiltigt värde för mängden data som lästes."},
        {"R_mismatchedStreamLength","Strömvärdet är inte den angivna längden. Den angivna längden är {0}, den faktiska längden är {1}."},
        {"R_notSupported","Den här åtgärden stöds inte."},
        {"R_invalidOutputParameter","Indexet {0} för utdataparametern är inte giltigt."},
        {"R_outputParameterNotRegisteredForOutput","Utdataparametern {0} registrerades inte för utdata."},
        {"R_parameterNotDefinedForProcedure","Parametern {0} definierades inte för den lagrade proceduren {1}."},
        {"R_connectionIsClosed","Anslutningen är stängd."},
        {"R_invalidBooleanValue","Egenskapen {0} innehåller inget giltigt booleskt värde. Endast true eller false kan användas."},
        {"R_propertyMaximumExceedsChars","Egenskapen {0} överskrider maxantalet {1} tecken."},
        {"R_invalidPortNumber","Portnumret {0} är inte giltigt."},
        {"R_invalidTimeOut","{0} är inte giltigt för timeout."},
        {"R_invalidLockTimeOut","{0} är inte giltigt för lockTimeOut."},
        {"R_invalidAuthenticationScheme","authenticationScheme {0} är inte giltigt."},
        {"R_invalidPacketSize","{0} är inte giltigt för packetSize."},
        {"R_packetSizeTooBigForSSL","Det går inte att använda SSL-kryptering på nätverkspaket större än {0} byte. Kontrollera anslutningsegenskaperna och konfigurationen av SQL Server."},
        {"R_tcpipConnectionFailed","TCP/IP-anslutningen till värddatorn {0}, port {1} misslyckades. Fel: \"{2}\"."},
        {"R_invalidTransactionLevel","Transaktionsnivån {0} är inte giltig."},
        {"R_cantInvokeRollback","Det går inte att anropa rollback-åtgärd när AutoCommit-läget är inställt på \"true\"."},
        {"R_cantSetSavepoint","Det går inte att ange en lagringspunkt när AutoCommit-läget är \"true\"."},
        {"R_sqlServerHoldability","SQL Server har endast stöd för kvarhållning på anslutningsnivå. Använd metoden connection.setHoldability()."},
        {"R_invalidHoldability","Värdet {0} för kvarhållning är ogiltigt."},
        {"R_invalidColumnArrayLength","Kolumnmatrisen är inte giltig. Längden måste vara 1."},
        {"R_valueNotSetForParameter","Värdet är inte angivet för parameternumret {0}."},
        {"R_sqlBrowserFailed","Anslutningen till värddatorn {0}, den namngivna instansen {1}, misslyckades. Fel: {2}. Verifiera server- och instansnamn och kontrollera att ingen brandvägg blockerar UDP-trafik till port 1434. Kontrollera även för SQL Server 2005 eller senare att tjänsten SQL Server Browser körs på värddatorn."},
        {"R_notConfiguredToListentcpip","Servern {0} är inte konfigurerad för att lyssna med TCP/IP."},
        {"R_cantIdentifyTableMetadata","Det gick inte att identifiera tabellen {0} för metadata."},
        {"R_metaDataErrorForParameter","Ett metadatafel för parametern {0} har uppstått."},
        {"R_invalidParameterNumber","Parameternumret {0} är inte giltigt."},
        {"R_noMetadata","Det finns inga metadata."},
        {"R_resultsetClosed","Resultatuppsättningen är stängd."},
        {"R_invalidColumnName","Kolumnnamnet {0} är inte giltigt."},
        {"R_resultsetNotUpdatable","Det går inte att uppdatera resultatuppsättningen."},
        {"R_indexOutOfRange","Indexet {0} är utanför intervallet."},
        {"R_savepointNotNamed","savepoint är inte namngiven."},
        {"R_savepointNamed","savepoint {0} är namngiven."},
        {"R_resultsetNoCurrentRow","Det finns ingen aktuell rad för resultatuppsättningen."},
        {"R_mustBeOnInsertRow","Markören står inte på infogningsraden."},
        {"R_mustNotBeOnInsertRow","Den begärda åtgärden är inte giltig på infogningsraden."},
        {"R_cantUpdateDeletedRow","Det går inte att uppdatera en borttagen rad."},
        {"R_noResultset","Uttrycket returnerade ingen resultatuppsättning."},
        {"R_resultsetGeneratedForUpdate","En resultatuppsättning skapades för uppdatering."},
        {"R_statementIsClosed","Uttrycket är stängt."},
        {"R_invalidRowcount","Maxantalet rader ({0}) för en resultatuppsättning får inte vara negativt."},
        {"R_invalidQueryTimeOutValue","Frågans timeout-värde {0} är inte giltigt."},
        {"R_invalidFetchDirection","Hämtningsriktningen {0} är inte giltig."},
        {"R_invalidFetchSize","Hämtningsstorleken får inte vara negativ."},
        {"R_noColumnParameterValue","Inga kolumnparametervärden för uppdatering av raden har angetts."},
        {"R_statementMustBeExecuted","Uttrycket måste köras innan ett resultat kan fås."},
        {"R_modeSuppliedNotValid","Det angivna läget är inte giltigt."},
        {"R_variantNotSupported","Datatypen \"variant\" stöds inte."},
        {"R_errorConnectionString","Anslutningssträngen innehåller ett namn eller värde med felaktigt format."},
        {"R_errorProcessingComplexQuery","Ett fel uppstod under bearbetning av den komplicerade frågan."},
        {"R_invalidOffset","Förskjutningen {0} är inte giltig."},
        {"R_nullConnection","Anslutnings-URL:en är null."},
        {"R_invalidConnection","Anslutnings-URL:en är ogiltig."},
        {"R_cannotTakeArgumentsPreparedOrCallable","Metoden {0} kan inte ta argument för ett PreparedStatement eller CallableStatement."},
        {"R_unsupportedConversionFromTo","Konverteringen från {0} till {1} stöds inte."},
        {"R_errorConvertingValue","Ett fel uppstod när värdet {0} konverterades till JDBC-datatypen {1}."},
        {"R_streamIsClosed","Strömmen är stängd."},
        {"R_invalidTDS","TDS-protokollströmmen är inte giltig."},
        {"R_unexpectedToken"," Oväntad token {0}."},
        {"R_selectNotPermittedinBatch","SELECT-uttrycket tillåts inte i en batch."},
        {"R_failedToCreateXAConnection","Det gick inte att skapa XA-kontrollanslutningen. Fel: \"{0}\""},
        {"R_codePageNotSupported","Teckentabellen {0} stöds inte i Java-miljön."},
        {"R_unknownSortId","SQL Server-sorteringen {0} stöds inte av den här drivrutinen."},
        {"R_unknownLCID","Windows-sorteringen {0} stöds inte av den här drivrutinen."},
        {"R_encodingErrorWritingTDS","Ett kodningsfel uppstod när en sträng skrevs till TDS-bufferten. Fel: \"{0}\""},
        {"R_processingError","Ett bearbetningsfel har uppstått: {0}"},
        {"R_requestedOpNotSupportedOnForward","Den begärda åtgärden stöds inte för framåtriktade resultatuppsättningar."},
        {"R_unsupportedCursor","Markörtypen stöds inte."},
        {"R_unsupportedCursorOperation","Den begärda åtgärden stöds inte med den här markörtypen."},
        {"R_unsupportedConcurrency","Det finns inte stöd för parallellkörning."},
        {"R_unsupportedCursorAndConcurrency","Kombinationen markörtyp/parallellkörning stöds inte."},
        {"R_stringReadError","Ett strängläsningsfel uppstod vid förskjutning:{0}."},
        {"R_stringWriteError","Ett strängskrivningsfel uppstod vid förskjutning:{0}."},
        {"R_stringNotInHex","Strängen har inte ett giltigt hexadecimalt format."},
        {"R_unknownType","Java-typen {0} stöds inte."},
        {"R_physicalConnectionIsClosed","Den fysiska anslutningen för den här poolanslutningen är stängd."},
        {"R_invalidDataSourceReference","Ogiltig referens till DataSource."},
        {"R_cantGetColumnValueFromDeletedRow","Det går inte att hämta ett värde från en borttagen rad."},
        {"R_cantGetUpdatedColumnValue","Det går inte att komma åt uppdaterade kolumner förrän updateRow() eller cancelRowUpdates() har anropats."},
        {"R_cantUpdateColumn","Det går inte att uppdatera kolumnvärdet."},
        {"R_positionedUpdatesNotSupported","Positionerade uppdateringar och borttagningar stöds inte."},
        {"R_invalidAutoGeneratedKeys","Parametervärdet {0} för autoGeneratedKeys är inte giltigt. Endast värdena Statement.RETURN_GENERATED_KEYS och Statement.NO_GENERATED_KEYS kan användas."},
        {"R_notConfiguredForIntegrated","Drivrutinen är inte konfigurerad för integrerad autentisering."},
        {"R_failoverPartnerWithoutDB","databaseName krävs när anslutningsegenskapen failoverPartner används."},
        {"R_invalidPartnerConfiguration","Databasen {0} på servern {1} är inte konfigurerad för databasspegling."},
        {"R_invaliddisableStatementPooling","Värdet {0} för disableStatementPooling är inte giltigt."},
        {"R_invalidselectMethod","selectMethod {0} är inte giltig."},
        {"R_invalidpropertyValue","Datatypen för anslutningsegenskapen {0} är inte giltig. Alla egenskaper för den här anslutningen ska vara av typen String."},
        {"R_invalidArgument","Argumentet {0} är ogiltigt."},
        {"R_streamWasNotMarkedBefore","Strömmen har inte markerats."},
        {"R_invalidresponseBuffering","responseBuffering-anslutningsegenskapen {0} är inte giltig."},
        {"R_invalidapplicationIntent","applicationIntent-anslutningsegenskapen {0} är inte giltig."},
        {"R_dataAlreadyAccessed","Data används redan och är inte tillgängliga för den här kolumnen eller parametern."},
        {"R_outParamsNotPermittedinBatch","Parametrarna OUT och INOUT tillåts inte i en batch."},
        {"R_sslRequiredNoServerSupport","Drivrutinen kunde inte upprätta en säker anslutning till SQL Server med SSL-kryptering (Secure Sockets Layer). Programmet begärde kryptering men servern stöder inte SSL."},
        {"R_sslRequiredByServer","Det krävs en krypterad anslutning med SSL (Secure Sockets Layer) för SQL Server-inloggningen."},
        {"R_sslFailed","Drivrutinen kunde inte upprätta en säker anslutning till SQL Server med SSL-kryptering (Secure Sockets Layer). Fel: \"{0}\"."},
        {"R_certNameFailed","Det gick inte att verifiera servernamnet i ett certifikat under SSL-initieringen (Secure Sockets Layer)."},
        {"R_failedToInitializeXA","Det gick inte att initiera den lagrade proceduren xp_sqljdbc_xa_init. Statusen är: {0}. Fel: \"{1}\""},
        {"R_failedFunctionXA","Funktionen {0} misslyckades. Statusen är: {1}. Fel: {2}"},
        {"R_noTransactionCookie","Funktionen {0} misslyckades. Ingen transaktions-cookie returnerades."},
        {"R_failedToEnlist","Det gick inte att registrera. Fel: \"{0}\""},
        {"R_failedToUnEnlist","Det gick inte att avregistrera. Fel: \"{0}\""},
        {"R_failedToReadRecoveryXIDs","Det gick inte att läsa XID:n (transaktions-ID:n för XA-förgreningar) för återställning. Fel: \"{0}\""},
        {"R_userPropertyDescription","Databasanvändaren."},
        {"R_passwordPropertyDescription","Lösenordet för databasen."},
        {"R_databaseNamePropertyDescription","Namnet på databasen som användaren ska ansluta till."},
        {"R_serverNamePropertyDescription","Datorn som kör SQL Server."},
        {"R_portNumberPropertyDescription","TCP-porten där en instans av SQL Server lyssnar."},
        {"R_serverSpnPropertyDescription","SQL Server-SPN."},
        {"R_columnEncryptionSettingPropertyDescription","Inställningen för kolumnkryptering."},
        {"R_serverNameAsACEPropertyDescription","Översätter serverName från Unicode till ASCII Compatible Encoding (ACE), enligt definitionen i ToASCII-operationen i RFC 3490."},
        {"R_sendStringParametersAsUnicodePropertyDescription","Avgör om strängparametrar skickas till servern som Unicode eller databasens teckenuppsättning."},
        {"R_multiSubnetFailoverPropertyDescription","Anger om programmet ansluter till Availability Group Listener för en Availability Group eller Failover Cluster Instance."},
        {"R_applicationNamePropertyDescription","Programnamnet för SQL Server-profilering och loggningsverktyg."},
        {"R_lastUpdateCountPropertyDescription","Ser till att endast det sista uppdateringsantalet returneras från ett SQL-uttryck som skickats till servern."},
        {"R_disableStatementPoolingPropertyDescription","Inaktiverar uttryckspoolfunktionen."},
        {"R_integratedSecurityPropertyDescription","Anger om Windows-autentisering ska användas vid anslutning till SQL Server."},
        {"R_authenticationSchemePropertyDescription","Det autentiseringsschema som ska användas för integrerad autentisering."},
        {"R_lockTimeoutPropertyDescription","Antalet millisekunder som databasen väntar innan den rapporterar en lås-timeout."},
        {"R_loginTimeoutPropertyDescription","Antalet millisekunder som drivrutinen väntar innan den gör en timeout för en misslyckad anslutning."},
        {"R_instanceNamePropertyDescription","Namnet på SQL Server-instansen som anslutningar görs till."},
        {"R_xopenStatesPropertyDescription","Avgör om drivrutinen returnerar XOPEN-kompatibla SQL-statuskoder i undantag."},
        {"R_selectMethodPropertyDescription","Gör att programmet kan använda servermarkörer för att bearbeta skrivskyddade, framåtriktade resultatuppsättningar."},
        {"R_responseBufferingPropertyDescription","Styr det adaptiva buffringsbeteendet för att programmet ska kunna bearbeta stora resultatuppsättningar utan att använda servermarkörer."},
        {"R_applicationIntentPropertyDescription","Deklarerar programmets belastningstyp vid anslutning till en server. Möjliga värden är ReadOnly och ReadWrite."},
        {"R_workstationIDPropertyDescription","Värddatornamnet för arbetsstationen."},
        {"R_failoverPartnerPropertyDescription","Namnet på servern för växling vid fel (failover) som används i en databasspeglingskonfiguration."},
        {"R_packetSizePropertyDescription","Nätverkspaketstorleken som används för att kommunicera med SQL Server."},
        {"R_encryptPropertyDescription","Avgör om SSL-kryptering (Secure Sockets Layer) ska användas mellan klienten och servern."},
        {"R_trustServerCertificatePropertyDescription","Avgör om drivrutinen ska validera SSL-certifikatet (Secure Sockets Layer) för SQL Server."},
        {"R_trustStoreTypePropertyDescription","Typ av förtroendearkiv såsom JKS/PKCS12 eller varje tillämpningstyp av FIPS-provider KeyStore."},
        {"R_trustStorePropertyDescription","Sökvägen till arkivfilen med betrodda certifikat."},
        {"R_trustStorePasswordPropertyDescription","Lösenordet som används för att kontrollera integriteten för betrodda arkivdata."},
        {"R_hostNameInCertificatePropertyDescription","Värddatornamnet som ska användas för att verifiera SSL-certifikatet (Secure Sockets Layer) för SQL Server."},
        {"R_sendTimeAsDatetimePropertyDescription","Anger om SQL Server-datatypen datetime ska användas för att skicka java.sql.Time-värden till databasen."},
        {"R_TransparentNetworkIPResolutionPropertyDescription","Bestämmer om funktionen Transparent Network IP Resolution ska användas."},
        {"R_queryTimeoutPropertyDescription","Antalet sekunder som databasen väntar innan den rapporterar en frågetimeout."},
        {"R_socketTimeoutPropertyDescription","Antal millisekunder innan java.net.SocketTimeoutException utlöses."},
        {"R_serverPreparedStatementDiscardThresholdPropertyDescription","Tröskelvärdet för när du vill stänga kasserade förberedda rapporter på servern (anropa ett parti av sp_unprepares). Ett värde på 1 eller mindre leder till att sp_unprepare anropas direkt vid PreparedStatment-stänging."},
        {"R_enablePrepareOnFirstPreparedStatementCallPropertyDescription","Den här inställningen anger om ett förberett uttryck förbereds (sp_prepexec) vid första användningen (egenskapen = true) eller vid andra efter att först ha anropat sp_executesql (egenskapen = false)."},
        {"R_statementPoolingCacheSizePropertyDescription","Den här inställningen anger storleken för det förberedda utdragscacheminnet för en anslutning. Ett värde mindre än 1 innebär inget cacheminne."},
        {"R_gsscredentialPropertyDescription","Personifierade GSS-autentiseringsuppgifter för åtkomst till SQL Server."},
        {"R_noParserSupport","Ett fel uppstod när den nödvändiga parsern initierades. Fel: \"{0}\""},
        {"R_writeOnlyXML","Det går inte att läsa från den här SQLXML-instansen. Det går endast att skriva data till den."},
        {"R_dataHasBeenReadXML","Det går inte att läsa från den här SQLXML-instansen. Data har redan lästs."},
        {"R_readOnlyXML","Det går inte att skriva till den här SQLXML-instansen. Det går endast att läsa data från den."},
        {"R_dataHasBeenSetXML","Det går inte att skriva till den här SQLXML-instansen. Data har redan angetts."},
        {"R_noDataXML","Inga data har angetts i den här SQLXML-instansen."},
        {"R_cantSetNull","Det går inte att ange ett null-värde."},
        {"R_failedToParseXML","Det gick inte att parsa XML. Fel: {0}"},
        {"R_isFreed","Det här objektet ({0}) har frigjorts. Det går inte längre att komma åt det."},
        {"R_invalidProperty","Den här egenskapen stöds inte: {0}."},
        {"R_referencingFailedTSP","Lösenordet för DataSource trustStore måste anges."},
        {"R_valueOutOfRange","Ett eller flera värden är inte i det tillåtna värdeintervallet för SQL Server-datatypen {0}"},
        {"R_integratedAuthenticationFailed","Integrerad autentisering misslyckades."},
        {"R_permissionDenied","Säkerhetsöverträdelse Behörighet till målet {0} nekades."},
        {"R_getSchemaError","Det uppstod ett fel vid hämtning av standardschemanamn."},
        {"R_setSchemaWarning","Varning: setSchema är inte ett valfritt alternativ i den här drivrutinsversionen."},
        {"R_updateCountOutofRange","Värdet för antal uppdateringar ligger utanför intervallet."},
        {"R_limitOffsetNotSupported","OFFSET-sats i begränsningsavbrottssekvensen stöds inte."},
        {"R_limitEscapeSyntaxError","Fel i ESCAPE-begränsningssyntax. Det gick inte att parsa frågan."},
        {"R_featureNotSupported","{0} stöds inte."},
        {"R_zoneOffsetError","Det uppstod ett fel vid hämtning av zonförskjutning."},
        {"R_invalidMaxRows","Det maximala radantal som stöds för en resultatuppsättning är Integer.MAX_VALUE eller mindre."},
        {"R_schemaMismatch","Käll- och målschemana överensstämmer inte."},
        {"R_invalidColumn","Kolumn {0} är ogiltig.  Kontrollera kolumnens mappningar."},
        {"R_invalidDestinationTable","Måltabellens namn saknas eller är ogiltigt."},
        {"R_unableRetrieveColMeta","Det går inte att hämta kolumnens metadata."},
        {"R_invalidDestConnection","Målanslutningen måste vara en anslutning från Microsoft JDBC Driver for SQL Server."},
        {"R_unableRetrieveSourceData","Det gick inte att hämta data från källan."},
        {"R_ParsingError","Det gick inte att parsa data för typen {0}."},
        {"R_BulkTypeNotSupported","Datatypen {0} stöds inte vid masskopiering."},
        {"R_invalidTransactionOption","Alternativet UseInternalTransaction kan inte ställas in på TRUE om det används med ett Connection-objekt."},
        {"R_invalidNegativeArg","Argumentet {0} kan inte vara negativt."},
        {"R_BulkColumnMappingsIsEmpty","Det går inte att genomföra någon masskopieringsåtgärd om den enda mappningen är en identitetskolumn och KeepIdentity har ställts in som falskt."},
        {"R_BulkCSVDataSchemaMismatch","Källdata överensstämmer inte med källschemat."},
        {"R_CSVDataSchemaMismatch","Källdata överensstämmer inte med källschemat."},
        {"R_BulkCSVDataDuplicateColumn","Duplicering av kolumnnamn är inte tillåtet."},
        {"R_invalidColumnOrdinal","Kolumn {0} är ogiltig. Kolumnnumret måste vara större än noll."},
        {"R_unsupportedEncoding","Kodningen {0} stöds inte."},
        {"R_UnexpectedDescribeParamFormat","Internt fel. Formatet för resultatuppsättningen som returnerades av sp_describe_parameter_encryption är ogiltigt. En av resultatuppsättningarna saknas."},
        {"R_InvalidEncryptionKeyOridnal","Internt fel. Det refererade ordningstalet {0} för kolumnkrypteringsnyckeln saknas i de krypteringsmetadata som returnerades av sp_describe_parameter_encryption. Det högsta ordningstalet är {1}."},
        {"R_MissingParamEncryptionMetadata","Internt fel. Metadata för några parametrar i uttrycket eller proceduren {0} saknas i resultatuppsättningen som returnerades av sp_describe_parameter_encryption."},
        {"R_UnableRetrieveParameterMetadata","Det går inte att hämta metadata för parameterkryptering."},
        {"R_InvalidCipherTextSize","Den angivna chiffertexten har den ogiltiga storleken {0} byte, vilket är under minimum på {1} byte som krävs för dekryptering."},
        {"R_InvalidAlgorithmVersion","Versionen {0} på krypteringsalgoritmen för den angivna chiffertexten matchar inte den förväntade versionen {1} på krypteringsalgoritmen."},
        {"R_InvalidAuthenticationTag","Den angivna chiffertexten har en ogiltig autentiseringstagg. "},
        {"R_EncryptionFailed","Internt fel vid kryptering:  {0} "},
        {"R_DecryptionFailed","Internt fel vid dekryptering:  {0} "},
        {"R_InvalidKeySize","Kolumnkrypteringsnyckeln har dekrypterats men dess längd {0} matchar inte längden {1} för algoritmen {2}. Verifiera det krypterade värdet för kolumnkrypteringsnyckeln i databasen."},
        {"R_InvalidEncryptionType","Krypteringstypen {0} som angivits för kolumnen i databasen är antingen ogiltig eller skadad. Giltiga krypteringstyper för algoritmen {1} är: {2}."},
        {"R_UnknownColumnEncryptionAlgorithm","Algoritmen {0} finns inte. Algoritmer som registrerats i fabriken är {1}."},
        {"R_KeyExtractionFailed","Nyckelextraheringen misslyckades: {0}."},
        {"R_UntrustedKeyPath","Sökvägen för kolumnhuvudnyckeln {0} som togs emot från servern {1} är inte en betrodd nyckelsökväg. Sökvägen för kolumnhuvudnyckeln kan vara skadad eller så bör du ställa in {0} som en betrodd nyckelsökväg med hjälp av SQLServerConnection.setColumnEncryptionTrustedMasterKeyPaths()."},
        {"R_UnrecognizedKeyStoreProviderName","Det gick inte att dekryptera en kolumnkrypteringsnyckel. Ogiltigt namn på provider av nyckellagring {0}. Namnet för en provider av nyckellagring måste antingen vara en av systemets providers av nyckellagring eller en registrerad anpassad provider av nyckellagring. Giltiga namn för systemets providers av nyckellagring är: {1}. Giltiga (för närvarande registrerade) namn för anpassad provider av nyckellagring är: {2}. Verifiera informationen för providern av nyckellagring i definitionerna för kolumnens huvudnyckeldefinitioner i databasen och verifiera att alla anpassade providers av nyckellagring som används i din app är korrekt registrerade."},
        {"R_UnsupportedDataTypeAE","Kryptering och dekryptering av datatypen {0} stöds inte."},
        {"R_NormalizationErrorAE","Dekryptering av datatypen {0} misslyckades. Normaliseringsfel."},
        {"R_UnsupportedNormalizationVersionAE","Normaliseringsversionen {0} som togs emot från SQL Server är antingen ogiltig eller skadad. Giltiga normaliseringsversioner är: {1}."},
        {"R_NullCipherTextAE","Internt fel. Ciphertext-värdet kan inte vara null."},
        {"R_NullColumnEncryptionAlgorithmAE","Internt fel. Krypteringsalgoritmen kan inte vara null. Giltiga algoritmer är: {1}."},
        {"R_CustomCipherAlgorithmNotSupportedAE","Anpassade chifferalgoritmer stöds inte."},
        {"R_PlainTextNullAE","Internt fel. Plaintext-värdet kan inte vara null."},
        {"R_StreamingDataTypeAE","Data med en längd över {0} stöds inte i den krypterade {1}-kolumnen."},
        {"R_AE_NotSupportedByServer","SQL Server-instansen som är i användning stöder inte kolumnkryptering."},
        {"R_InvalidAEVersionNumber","Ett ogiltigt versionsnummer {0} togs emot för Always Encrypted."},
        {"R_NullEncryptedColumnEncryptionKey","Internt fel. Den krypterade kolumnkrypteringsnyckeln kan inte vara null."},
        {"R_EmptyEncryptedColumnEncryptionKey","Internt fel. En tom krypterad kolumnkrypteringsnyckel angavs."},
        {"R_InvalidMasterKeyDetails","Ogiltig information angavs för huvudnyckeln."},
        {"R_CertificateError","Ett fel uppstod vid hämtning av certifikatet {0} från nyckellagringen {1}."},
        {"R_ByteToShortConversion","Ett fel uppstod vid dekryptering av kolumnkrypteringsnyckeln."},
        {"R_InvalidCertificateSignature","Den angivna signaturen för den krypterade kolumnkrypteringsnyckeln matchar inte signaturen som beräknats med kolumnens huvudnyckel (certifikat) i {0}. Den krypterade kolumnkrypteringsnyckeln kan vara skadad, eller så är den angivna sökvägen felaktig."},
        {"R_CEKDecryptionFailed","Undantag vid dekryptering av krypterad kolumnkrypteringsnyckel:  {0} "},
        {"R_NullKeyEncryptionAlgorithm","Algoritmen för nyckelkryptering kan inte vara null."},
        {"R_NullKeyEncryptionAlgorithmInternal","Internt fel. Algoritmen för nyckelkryptering kan inte vara null."},
        {"R_InvalidKeyEncryptionAlgorithm","Ogiltig algoritm för nyckelkryptering angavs: {0}. Förväntat värde: {1}."},
        {"R_InvalidKeyEncryptionAlgorithmInternal","Internt fel. Ogiltig algoritm för nyckelkryptering angavs: {0}. Förväntat värde: {1}."},
        {"R_NullColumnEncryptionKey","Kolumnkrypteringsnyckeln kan inte vara null."},
        {"R_EmptyColumnEncryptionKey","En tom kolumnkrypteringsnyckel har angetts."},
        {"R_CertificateNotFoundForAlias","Certifikatet med alias {0} hittades inte i lagringen som angavs av {1}. Verifiera att certifikatet har importerats korrekt till certifikatplatsen/lagringen."},
        {"R_UnrecoverableKeyAE","Det går inte att återställa den privata nyckeln från nyckellagringen med certifikatinformationen {0}.  Verifiera att det importerade AE-certifikatet innehåller privata nycklar och lösenord som är korrekta för certifikatet."},
        {"R_KeyStoreNotFound","Systemet kan inte hitta nyckellagringsfilen på den angivna sökvägen. Verifiera att sökvägen är korrekt och att du har behörighet att komma åt den."},
        {"R_CustomKeyStoreProviderMapNull","Kartan för lagringsprovider för kolumnkrypteringsnyckeln kan inte vara null. Ett icke-null värde är förväntat."},
        {"R_EmptyCustomKeyStoreProviderName","Ogiltigt providernamn för nyckellagring angavs. Namn för nyckellagringsproviders kan inte vara null eller tomt."},
        {"R_InvalidCustomKeyStoreProviderName","Ogiltigt namn på nyckellagringsprovider: {0}. Prefixet {1} är reserverat för systemets nyckellagringsproviders."},
        {"R_CustomKeyStoreProviderValueNull","Null-referens angiven för nyckellagringsprovider {0}. Ett icke-nullvärde förväntades."},
        {"R_CustomKeyStoreProviderSetOnce","Nyckellagringsproviders kan inte ställas in mer än en gång."},
        {"R_unknownColumnEncryptionType","Ogiltig kolumnkrypteringstyp {0}."},
        {"R_unsupportedStmtColEncSetting","SQLServerStatementColumnEncryptionSetting kan inte vara null."},
        {"R_unsupportedConversionAE","Konverteringen från {0} till {1} stöds inte för kolumnkryptering."},
        {"R_InvalidDataForAE","Det angivna värdet för typen {0} från datakällan kan inte konverteras till typen {1} för den angivna målkolumnen."},
        {"R_authenticationPropertyDescription","Autentiseringen som ska användas."},
        {"R_accessTokenPropertyDescription","Åtkomsttoken som ska användas för Azure Active Directory."},
        {"R_FedAuthRequiredPreLoginResponseInvalidValue","Servern skickade ett oväntat värde för alternativet FedAuthRequired PreLogin. Värdet var {0}."},
        {"R_FedAuthInfoLengthTooShortForCountOfInfoIds","FedAuthInfo-token måste innehålla minst 4 byte som anger antalet info-ID:n."},
        {"R_FedAuthInfoInvalidOffset","FedAuthInfoDataOffset pekar till en ogiltig plats. Aktuell dataOffset är {0}."},
        {"R_FedAuthInfoFailedToReadData","Det gick inte att läsa in FedAuthInfoData."},
        {"R_FedAuthInfoLengthTooShortForData","FEDAUTHINFO-tokenströmmen är inte tillräckligt lång ({0}) för att innehålla de data den hävdar."},
        {"R_FedAuthInfoDoesNotContainStsurlAndSpn","FEDAUTHINFO-tokenströmmen innehåller inte både STSURL och SPN."},
        {"R_ADALExecution","Det gick inte att autentisera användaren {0} i Active Directory (Authentication={1})."},
        {"R_UnrequestedFeatureAckReceived","Ej begärd funktionsbekräftelse mottogs. Funktions-ID {0}."},
        {"R_FedAuthFeatureAckContainsExtraData","Funktionstilläggs-ACK för federerad autentisering för ADAL och Security Token inkluderar extra data."},
        {"R_FedAuthFeatureAckUnknownLibraryType","Försöker använda okänt federerat autentiseringsbibliotek. Biblioteks-ID {0}."},
        {"R_UnknownFeatureAck","Okänd funktionsbekräftelse mottagen."},
        {"R_SetAuthenticationWhenIntegratedSecurityTrue","Det går inte att ställa in \"Authentication\" med \"IntegratedSecurity\" till värdet \"sant\"."},
        {"R_SetAccesstokenWhenIntegratedSecurityTrue","Det går inte att ställa in AccessToken-egenskapen om nyckelordet för anslutningssträngen för \"IntegratedSecurity\" är inställd på \"sant\"."},
        {"R_IntegratedAuthenticationWithUserPassword","Det går inte att använda \"Authentication=ActiveDirectoryIntegrated\" med nyckelorden \"User\", \"UserName\" eller \"Password\" för anslutningssträngen."},
        {"R_AccessTokenWithUserPassword","Det går inte att ställa in AccessToken-egenskapen om \"User\", \"UserName\" eller \"Password\" har angivits i anslutningssträngen."},
        {"R_AccessTokenCannotBeEmpty","AccesToken kan inte vara tomt."},
        {"R_SetBothAuthenticationAndAccessToken","Det går inte att ställa in AccessToken-egenskapen om \"Authentication\" har angivits i anslutningssträngen."},
        {"R_NoUserPasswordForActivePassword","Båda nyckelorden \"User\" (eller \"UserName\") och \"Password\" för anslutningssträngen måste anges om \"Authentication=ActiveDirectoryPassword\"."},
        {"R_NoUserPasswordForSqlPassword","Båda nyckelorden \"User\" (eller \"UserName\") och \"Password\" för anslutningssträngen måste anges om \"Authentication=SqlPassword\"."},
        {"R_ForceEncryptionTrue_HonorAEFalse","Det går inte att ställa in Tvinga kryptering till sant för parametern {0}, eftersom kryptering inte har aktiverats för uttrycket eller proceduren {1}."},
        {"R_ForceEncryptionTrue_HonorAETrue_UnencryptedColumn","Det går inte att köra uttrycket eller proceduren {0} eftersom Tvinga kryptering har ställts in på sant för parametern {1} och databasen förväntar sig att parametern skickas som klartext. Detta kan bero på ett konfigurationsfel."},
        {"R_ForceEncryptionTrue_HonorAEFalseRS","Det går inte att ställa in Tvinga kryptering till sant för parametern {0}, eftersom kryptering inte har aktiverats för uttrycket eller proceduren."},
        {"R_ForceEncryptionTrue_HonorAETrue_UnencryptedColumnRS","Det går inte att köra uppdatering eftersom Tvinga kryptering har ställs in på sant för parametern {0} och databasen förväntar sig att parametern skickas som klartext. Detta kan bero på ett konfigurationsfel."},
        {"R_NullValue","{0} kan inte vara null."},
        {"R_AKVPathNull","Nyckelsökvägen för Azure Key Vault kan inte vara null."},
        {"R_AKVURLInvalid","Ogiltig URL har angetts: {0}."},
        {"R_AKVMasterKeyPathInvalid","Ogiltig nyckelsökväg för Azure Key Vault har angetts: {0}."},
        {"R_EmptyCEK","En tom kolumnkrypteringsnyckel har angetts."},
        {"R_EncryptedCEKNull","Den krypterade kolumnkrypteringsnyckeln kan inte vara null."},
        {"R_EmptyEncryptedCEK","Längden för den krypterade kolumnkrypteringsnyckeln får inte vara noll."},
        {"R_NonRSAKey","Det går inte att använda en nyckel som inte är RSA: {0}."},
        {"R_GetAKVKeySize","Det går inte att hämta den offentliga nyckelstorleken för Azure Key Vault i byte."},
        {"R_InvalidEcryptionAlgorithmVersion","Den angivna krypterade kolumnkrypteringsnyckeln innehåller en ogiltig krypteringsalgoritmversion {0}. Förväntad version är {1}."},
        {"R_AKVKeyLengthError","Den angivna krypterade kolumnkrypteringsnyckelns ciphertext-längd {0}, matchar inte chiffertextens längd {1} vid användning av kolumnens huvudnyckel (Azure Key Vault-nyckeln) i {2}. Den krypterade kolumnkrypteringsnyckeln kan vara skadad, eller så är den angivna nyckelsökvägen till Azure Key Vault felaktig."},
        {"R_AKVSignatureLengthError","Den angivna krypterade kolumnkrypteringsnyckelns signaturlängd {0}, matchar inte signaturlängden {1} vid användning av kolumnens huvudnyckel (Azure Key Vault-nyckel) i {2}. Den krypterade kolumnkrypteringsnyckeln kan vara skadad, eller så är den angivna nyckelsökvägen till Azure Key Vault felaktig."},
        {"R_HashNull","Hash får inte vara null vid dekryptering av en krypterad kolumnkrypteringsnyckel."},
        {"R_NoSHA256Algorithm","SHA-256-algoritmen stöds inte."},
        {"R_VerifySignature","Det går inte att verifiera signaturen för kolumnkrypteringsnyckeln."},
        {"R_CEKSignatureNotMatchCMK","Den angivna krypterade kolumnkrypteringsnyckelns signatur matchar inte signaturen som beräknades med kolumnens huvudnyckel (Assymetrisk nyckel i Azure Key Vault) i {0}. Den krypterade kolumnkrypteringsnyckeln kan vara skadad, eller så är den angivna sökvägen felaktig."},
        {"R_DecryptCEKError","Det går inte att dekryptera CEK med den angivna Azure Key Vault-nyckeln."},
        {"R_EncryptCEKError","Det går inte att kryptera CEK med den angivna Azure Key Vault-nyckeln."},
        {"R_CipherTextLengthNotMatchRSASize","CipherText-längden matchar inte RSA-nyckelstorleken."},
        {"R_GenerateSignature","Det går inte att generera signaturen med en angiven nyckel-URL för Azure Key Vault."},
        {"R_SignedHashLengthError","Den signerade hash-längden matchar inte RSA-nyckelstorleken."},
        {"R_InvalidSignatureComputed","Ogiltig signatur beräknades för den krypterade kolumnkrypteringsnyckeln."},
        {"R_UnableLoadADALSqlDll","Det går inte att läsa in adalsql.dll. Felkod: 0x{0}. För information, se: http://go.microsoft.com/fwlink/?LinkID=513072"},
        {"R_ADALAuthenticationMiddleErrorMessage","Felkod 0x{0}; tillstånd {1}."},
        {"R_unsupportedDataTypeTVP","Datatypen {0} stöds inte i Table-Valued Parameter."},
        {"R_moreDataInRowThanColumnInTVP","Indatamatrisen är längre än antalet kolumner i den här tabellen."},
        {"R_invalidTVPName"," Table-Valued Parameter måste ha ett giltigt typnamn."},
        {"R_invalidThreePartName","Ogiltigt tredelat namnformat för TypeName."},
        {"R_unsupportedConversionTVP","Konverteringen från {0} till {1} stöds inte för Table-Valued Parameter."},
        {"R_TVPMixedSource","Det går inte att lägga till kolumnmetadata. Table-Valued Parameter har en ResultSet som metadata härleds från."},
        {"R_TVPEmptyMetadata","Det finns inte tillräckligt med fält i den strukturerade typen. Strukturerade typer måste ha minst ett fält."},
        {"R_TVPInvalidValue","Värdet som angivits för Table-Valued Parameter {0} är inte giltigt. Bara SQLServerDataTable-, ResultSet- och ISQLServerDataRecord-objekt stöds."},
        {"R_TVPInvalidColumnValue","Indata är inte i korrekt format."},
        {"R_AADIntegratedOnNonWindows","ActiveDirectoryIntegrated stöds bara i Windows-operativsystem."},
        {"R_TVPSortOrdinalGreaterThanFieldCount","Sorteringsordningen {0} i fältet {1} överskrider det totala antalet fält."},
        {"R_TVPMissingSortOrderOrOrdinal","Antingen båda eller ingendera av sorteringsordning och ordningstal måste anges (SortOrder.Unspecified och -1). De värden som angavs var: ordning = {0}, ordningstal = {1}."},
        {"R_TVPDuplicateSortOrdinal","Sorteringsordningen {0} angavs två gånger."},
        {"R_TVPMissingSortOrdinal","Sorteringsordningen {0} angavs inte."},
        {"R_TVPDuplicateColumnName","Det finns redan ett kolumnnamn {0} som tillhör den här SQLServerDataTable."},
        {"R_InvalidConnectionSetting","{0}-värdet {1} är inte giltigt."},
        {"R_InvalidWindowsCertificateStoreEncryption","Det går inte att kryptera en kolumnkrypteringsnyckel med Windows Certificate Store."},
        {"R_AEKeypathEmpty","Internt fel. Certifikatsökvägen får inte vara null. Använd följande format: \"certifikatplats/certifikatlager/certifikatets tumavtryck\", där \"certifikatplats\" antingen är LocalMachine eller CurrentUser."},
        {"R_AEWinApiErr","Internt fel i Windows Api."},
        {"R_AECertpathBad","Internt fel. Ogiltig certifikatsökväg: {0}. Använd följande format: \"certifikatplats/certifikatlager/certifikatets tumavtryck\", där \"certifikatplats\" antingen är LocalMachine eller CurrentUser."},
        {"R_AECertLocBad","Internt fel. Ogiltig certifikatplats {0} i certifikatsökvägen {1}. Använd följande format: \"certifikatplats/certifikatlager/certifikatets tumavtryck\", där \"certifikatplats\" antingen är LocalMachine eller CurrentUser."},
        {"R_AECertStoreBad","Internt fel. Ogiltigt certifikatlager {0} angavs i certifikatsökvägen {1}. Förväntat värde: My."},
        {"R_AECertHashEmpty","Internt fel. Tomt tumavtryck för certifikat angavs i certifikatsökvägen {0}."},
        {"R_AECertNotFound","Certifikatet med tumavtrycket {2} hittades inte i certifikatlagret {1} på certifikatplatsen {0}. Verifiera att certifikatsökvägen i kolumnens huvudnyckeldefinition i databasen är korrekt och att certifikatet har importerats korrekt till certifikatplatsen/lagret."},
        {"R_AEMaloc","Minnesallokeringsfel."},
        {"R_AEKeypathLong","Internt fel. Den angivna certifikatsökvägen innehåller {0} byte, vilket överskrider maxlängden på {1} byte."},
        {"R_AEECEKLenBad","Den angivna krypterade kolumnkrypteringsnyckelns ciphertext-längd {0}, matchar inte chiffertextlängden {1} vid användning av kolumnens huvudnyckel (certifikat) i {2}. Den krypterade kolumnkrypteringsnyckeln kan vara skadad, eller så är den angivna certifikatsökvägen felaktig."},
        {"R_AEECEKSigLenBad","Den angivna krypterade kolumnkrypteringsnyckelns signaturlängd {0}, matchar inte längden {1} vid användning av kolumnens huvudnyckel (certifikat) i {2}. Den krypterade kolumnens krypteringsnyckel kan vara skadad, eller så är det angivna certifikatsökvägen felaktig."},
        {"R_AEKeyPathEmptyOrReserved","Certifikatsökvägen {0} är ogiltig. Den är tom eller innehåller reserverade katalognamn."},
        {"R_AEKeyPathCurUser","CurrentUser angavs i nyckelsökvägen men ett fel uppstod vid hämtning av den nuvarande användarens ursprungliga arbetskatalog."},
        {"R_AEKeyFileOpenError","Fel vid öppning av certifikatfilen {0}."},
        {"R_AEKeyFileReadError","Fel vid läsning av certifikatfilen {0}."},
        {"R_keyStoreAuthenticationPropertyDescription","Namnet som identifierar ett nyckellager."},
        {"R_keyStoreSecretPropertyDescription","Autentiseringshemligheten eller information som behövs för att hitta hemligheten."},
        {"R_keyStoreLocationPropertyDescription","KeyStore-platsen."},
        {"R_fipsProviderPropertyDescription","FIPS-provider."},
        {"R_keyStoreAuthenticationNotSet","Nyckelordet \"keyStoreAuthentication\" för anslutningssträngen måste anges,  om {0} är angiven."},
        {"R_keyStoreSecretOrLocationNotSet","Du måste ange både keyStoreSecret och keyStoreLocation om keyStoreAuthentication=JavaKeyStorePassword har angetts i anslutningssträngen."},
        {"R_certificateStoreInvalidKeyword","Det går inte att ställa in keyStoreSecret om keyStoreAuthentication=CertificateStore har angetts in anslutningssträngen."},
        {"R_certificateStoreLocationNotSet","Du måste ange keyStoreLocation om keyStoreAuthentication=CertificateStore har angetts i anslutningssträngen."},
        {"R_certificateStorePlatformInvalid","Det går inte att ställa in keyStoreAuthentication=CertificateStore i ett Windows-operativsystem."},
        {"R_invalidKeyStoreFile","Det går inte att parsa {0}. Antingen så är filformatet inte giltigt eller så är lösenordet felaktigt."},
        {"R_invalidCEKCacheTtl","Ogiltig Time to Live har angetts för kolumnkrypteringsnyckelns cache. columnEncryptionKeyCacheTtl-värdet får inte vara negativt och timeUnit kan bara vara DAYS, HOURS, MINUTES eller SECONDS."},
        {"R_sendTimeAsDateTimeForAE","Använd sendTimeAsDateTime=false med Alltid krypterad."},
        {"R_TVPnotWorkWithSetObjectResultSet","setObject() med ResultSet stöds inte för Table-Valued-parameter. Använd setStructured()"},
        {"R_invalidQueryTimeout","queryTimeout {0} är ogiltig."},
        {"R_invalidSocketTimeout","socketTimeout {0} är ogiltig."},
        {"R_fipsPropertyDescription","Avgör om FIPS-kompatibel SSL-anslutning ska aktiveras mellan klienten och servern."},
        {"R_invalidFipsConfig","Det gick inte att aktivera FIPS."},
        {"R_invalidFipsEncryptConfig","Det gick inte att aktivera FIPS på grund av att någon kryptering inte är sann eller användning av betrodda certifikatinställningar."},
        {"R_invalidFipsProviderConfig","Det gick inte att aktivera FIPS på grund av ogiltig FIPSProvider eller TrustStoreType."},
        {"R_serverPreparedStatementDiscardThreshold","serverPreparedStatementDiscardThreshold {0} är ogiltig."},
        {"R_statementPoolingCacheSize","StatementPoolingCacheSize {0} är ogiltigt."},
        {"R_kerberosLoginFailedForUsername","Det går inte att logga in med Kerberos-huvudnamn {0}, kontrollera dina autentiseringsuppgifter. {1}"},
        {"R_kerberosLoginFailed","Kerberos-inloggning misslyckades: {0} på grund av {1} ({2})"},
        {"R_StoredProcedureNotFound","Kunde inte hitta den lagrade proceduren {0}."},
        {"R_jaasConfigurationNamePropertyDescription","Konfigurationsfil för inloggning för Kerberos-autentisering."},
    };
}
